INITIAL_USERS = [
    {
        "real_name": "Дамир",
        "username": "best_prepod",
        "access_level": "admin",
    },
    {
        "real_name": "Кирилл",
        "last_name": "Кипчарский",
        "payment_amount": 0,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Ярослав",
        "last_name": "Горбань",
        "payment_amount": 195,
        "max_lessons": 8,
        "access_level": "student",
    },
    {
        "real_name": "Ира",
        "last_name": "Гыра",
        "payment_amount": 70,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Даня",
        "last_name": "Оврашко",
        "payment_amount": 30,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Артём",
        "last_name": "Лысюк",
        "payment_amount": 70,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Максим",
        "last_name": "Седюк",
        "payment_amount": 70,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Назар",
        "last_name": "Сулима",
        "payment_amount": 70,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Дима",
        "last_name": "Ляшенко",
        "payment_amount": 70,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Илья",
        "last_name": "Слонь",
        "payment_amount": 1700,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Дамир",
        "last_name": "Лукьяненко",
        "payment_amount": 0,
        "max_lessons": 8,
        "access_level": "student",
    },
    {
        "real_name": "Андрей",
        "last_name": "Сидаш",
        "payment_amount": 85,
        "max_lessons": 4,
        "access_level": "student",
    },
]