from src.users.types import StudentT, StudentT

STUDENT_LIST: list[StudentT] = [
    {
        # "user_id": 6708135428,
        "real_name": "Оля",
        "last_name": "Лукьяненко",
        "payment_amount": 2500,
        "max_lessons": 8,
    },
    {
        # "user_id": 782692408,
        "real_name": "Кирилл",
        "last_name": "Кипчарский",
        "payment_amount": 3500,
        "max_lessons": 8,
    },
    {
        # "user_id": 549683719,
        "real_name": "Ярослав",
        "last_name": "Горбань",
        "payment_amount": 3300,
        "max_lessons": 8,
    },
    {
        # "user_id": 1898742332,
        "real_name": "Ира",
        "last_name": "Гыра",
        "payment_amount": 3500,
        "max_lessons": 8,
    },
    {
        # "user_id": 1402095363,
        "real_name": "Даня",
        "last_name": "Оврашко",
        "payment_amount": 1600,
        "max_lessons": 4,
    },
    {
        # "user_id": 5558192771,
        "real_name": "Артём",
        "last_name": "Лысюк",
        "payment_amount": 2000,
        "max_lessons": 4,
    },
    {
        # "user_id": 916570935,
        "real_name": "Максим",
        "last_name": "Седюк",
        "payment_amount": 2000,
        "max_lessons": 4,
    },
    {
        # "user_id": 736696668,
        "real_name": "Назар",
        "last_name": "Сулима",
        "payment_amount": 2000,
        "max_lessons": 4,
    },
    {
        # "user_id": 782694924,
        "real_name": "Олег",
        "last_name": "Голованенко",
        "payment_amount": 2300,
        "max_lessons": 4,
    },
    {
        # "user_id": 1356631201,
        "real_name": "Дима",
        "last_name": "Ляшенко",
        "payment_amount": 2000,
        "max_lessons": 4,
    },
    {
        # "user_id": 1322753193,
        "real_name": "Илья",
        "last_name": "Слонь",
        "payment_amount": 1800,
        "max_lessons": 4,
    },
]