INITIAL_USERS = [
    {
        "real_name": "Дамир",
        "username": "best_prepod",
        "access_level": "admin",
    },
    {
        "real_name": "Оля",
        "last_name": "Лукьяненко",
        "payment_amount": 2500,
        "max_lessons": 8,
        "access_level": "student",
    },
    {
        "real_name": "Кирилл",
        "last_name": "Кипчарский",
        "payment_amount": 3840,
        "max_lessons": 8,
        "access_level": "student",
    },
    {
        "real_name": "Ярослав",
        "last_name": "Горбань",
        "payment_amount": 3840,
        "max_lessons": 8,
        "access_level": "student",
    },
    {
        "real_name": "Ира",
        "last_name": "Гыра",
        "payment_amount": 2400,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Даня",
        "last_name": "Оврашко",
        "payment_amount": 2400,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Артём",
        "last_name": "Лысюк",
        "payment_amount": 2400,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Максим",
        "last_name": "Седюк",
        "payment_amount": 2400,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Назар",
        "last_name": "Сулима",
        "payment_amount": 2400,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Олег",
        "last_name": "Голованенко",
        "payment_amount": 2400,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Дима",
        "last_name": "Ляшенко",
        "payment_amount": 2400,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Илья",
        "last_name": "Слонь",
        "payment_amount": 1700,
        "max_lessons": 4,
        "access_level": "student",
    },
    {
        "real_name": "Никита",
        "last_name": "Шуменко",
        "payment_amount": 1700,
        "max_lessons": 4,
        "access_level": "student",
    }
]